language: java
jdk:
  - openjdk8

notification:
  email:
    recipients:
      - 568338536@qq.com
    on_success: change
    on_failure: always

script:
  - mvn clean package -DskipTests=true

branches:
  only:
    - master